name: Build, Test and Lint

on:
  workflow_dispatch:
  push:
    paths:
      - "go.mod"
      - "go.sum"
      - "**.go"
    branches:
      - "master"
  pull_request:
    paths:
      - "go.mod"
      - "go.sum"
      - "**.go"
    branches:
      - "master"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: Lint
        run: make lint
      - name: Test
        run: make test
